[DEV-24810] uses URL api instead of string interpolation
betterplace/betterplace-react-components pull request #66
Opened 2024-12-05 09:02 UTC by diego-souza

DEV-24810

uses URL api instead of string interpolation

Previously URLs that already had parameters
would have two question marks "?"

2024-12-05 15:30 UTC, liesas approved these changes

2024-12-05 19:44 UTC, iz-podpolja requested changes

2024-12-06 08:21 UTC, diego-souza commented on src/helpers/sharing_helper.ts
> +  for (const [key, value] of params.entries()) {
I'm following what comes from this:
```js
export type BaseShareActionArgs = { shareUrl: string; utmParams?: Record<string, any>; teaser?: string }
```
I changed the entries call.

2025-07-10 13:03 UTC, diego-souza commented
Finished in other PR according to Jörg here: https://betterplace.atlassian.net/browse/DEV-24810?focusedCommentId=37957

2025-07-10 13:03 UTC, closed without merging